# -*- coding: utf-8 -*-
"""把 scripts/data_prep.py 的內容注入 llama32-taiwanchat-qlora.ipynb 的共用模組 cell。

llama32-taiwanchat-qlora.ipynb 必須保持「單一檔案、可直接上傳 Colab」,因此共用邏輯以
實體複本嵌入 notebook;本腳本讓複本永遠機械同步、不可能默默漂移:

    python scripts/sync_notebook.py            # 注入(覆寫哨兵 cell)
    python scripts/sync_notebook.py --check    # 只比對:漂移則 exit 1

哨兵 cell 的辨識依據是第一行的 SENTINEL 字串。只用標準函式庫(json/hashlib)。
"""

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTEBOOK = ROOT / "llama32-taiwanchat-qlora.ipynb"
SOURCE = ROOT / "scripts" / "data_prep.py"
SENTINEL = "# %%DATA_PREP_MODULE%%"


def build_cell_source(src_text):
    sha = hashlib.sha256(src_text.encode("utf-8")).hexdigest()
    banner = (
        f"{SENTINEL}  AUTOGENERATED from scripts/data_prep.py — 不要直接改這個 cell!\n"
        f"# 請改 scripts/data_prep.py,然後執行:python scripts/sync_notebook.py\n"
        f"# sha256(scripts/data_prep.py) = {sha}\n"
    )
    return (banner + src_text).splitlines(keepends=True)


def find_sentinel_cell(nb):
    hits = [
        cell for cell in nb["cells"]
        if cell["cell_type"] == "code"
        and cell["source"]
        and cell["source"][0].startswith(SENTINEL)
    ]
    if len(hits) != 1:
        sys.exit(f"錯誤:notebook 裡找到 {len(hits)} 個哨兵 cell(應為 1)")
    return hits[0]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="只比對,不寫入;漂移 exit 1")
    args = parser.parse_args()

    src_text = SOURCE.read_text(encoding="utf-8")
    expected = build_cell_source(src_text)
    nb = json.loads(NOTEBOOK.read_text(encoding="utf-8"))
    cell = find_sentinel_cell(nb)

    if cell["source"] == expected:
        print("OK:notebook 內的共用模組 cell 與 scripts/data_prep.py 一致。")
        return

    if args.check:
        sys.exit(
            "漂移偵測:notebook 的共用模組 cell 與 scripts/data_prep.py 不一致!\n"
            "請執行:python scripts/sync_notebook.py"
        )

    cell["source"] = expected
    cell["outputs"] = []
    cell["execution_count"] = None
    cell.setdefault("metadata", {})["tags"] = ["shared-data-prep"]
    NOTEBOOK.write_text(
        json.dumps(nb, ensure_ascii=False, indent=1) + "\n", encoding="utf-8"
    )
    print("已注入 scripts/data_prep.py → llama32-taiwanchat-qlora.ipynb(哨兵 cell 已更新)。")


if __name__ == "__main__":
    main()
